apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
data:
  POSTGRES_USER: ${POSTGRES_USER}  # Remplacez par votre nom d'utilisateur encodé en base64
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Remplacez par votre mot de passe encodé en base64
