apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  REDIS_HOST: ${REDIS_HOST}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}