version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always

  poll:
    build:
      context: ./poll
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - redis
    restart: always

  db:
    image: postgres
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
    restart: always

  worker:
    build: ./worker
    networks:
      - back-tier
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - redis
      - db
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:


volumes:
  db-data:
